; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:tx]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<tx/> +<common/>
build_flags = 
	-DBUILD_TX
	-Os
	-DNDEBUG
	-Wl,--gc-sections
monitor_speed = 115200
lib_deps = 
	https://github.com/ElectronicCats/mpu6050
	mikalhart/TinyGPSPlus@^1.1.0
board_build.partitions = huge_app.csv
[env:rx]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<rx/>
build_flags = 
	-DBUILD_RX
	-DCORE_DEBUG_LEVEL=0
monitor_speed = 115200